include_guard(GLOBAL)

function(appellate_select_cmake_bracket_delimiter output_open output_close)
    if(ARGC LESS 3)
        message(FATAL_ERROR "At least one literal variable is required")
    endif()

    set(_equals "=")
    while(TRUE)
        set(_close "]${_equals}]")
        set(_collision OFF)
        foreach(_variable_name IN LISTS ARGN)
            if(NOT DEFINED ${_variable_name})
                message(FATAL_ERROR "Literal variable is not defined: ${_variable_name}")
            endif()
            string(FIND "${${_variable_name}}" "${_close}" _position)
            if(NOT _position EQUAL -1)
                set(_collision ON)
                break()
            endif()
        endforeach()
        if(NOT _collision)
            break()
        endif()
        string(APPEND _equals "=")
    endwhile()

    set(${output_open} "[${_equals}[" PARENT_SCOPE)
    set(${output_close} "]${_equals}]" PARENT_SCOPE)
endfunction()
